env {
  job.mode = "BATCH"
  parallelism = 1
}

source {
  FakeSource {
    row.num = 5
    schema {
      fields {
        id = "bigint"
        name = "string"
        age = "int"
        score = "double"
        active = "boolean"
      }
    }
    string.fake.mode = "name"
  }
}

sink {
  Console {
    log.print.data = true
  }
}
